### ISSUE TITLE
Admin Styles: Framework Compatability

### ISSUE THREAD

**Issue by israelidanny** [punkave/apostrophe#101]
I'm facing a few instances where I'm given a site to migrate to Apostrophe.

A site could be using a CSS framework, Bootstrap & Foundation being the mature and popular ones.

Could we consider making the LESS of the site a bit more extrenal-framework-proof? 

Right now it's dead easy to integrate foundation or bootstrap, but doing so introduces a few glitches to the admin interface (inputs, paddings, line heights, e.t.c).

A solution could be to introduce a few abstract resets in a LESS that would be applied to the admin classes and their children, to keep the design uniform no matter what framework is being introduced.

**Comment by benirose** [comment]
We don't have plans to address this any time soon, however it's possible that we might refactor some of our CSS in tandem with some of our backend refactors. I'm putting this in the backlog for now and we'll update if we address any of it.

**Comment by benirose** [comment]
We've been making some progress on this as a current project requires bootstrap. The biggest offender is that we rely on our reset.less to remove default styling (bullets, margin, and padding) on li tags, which is pretty silly. As I find them, I am adding those specific styles to the classes that need them.

**Comment by boutell** [comment]
Ben, is reset.less in Apostrophe itself, or just in our sandbox stuff? I
think it's fine in the latter because nobody has to use it... right?

On Mon, Sep 28, 2015 at 5:46 PM, benirose <notifications@github.com> wrote:

> We've been making some progress on this as a current project requires
> bootstrap. The biggest offender is that we rely on our reset.less to remove
> default styling (bullets, margin, and padding) on li tags, which is pretty
> silly. As I find them, I am adding those specific styles to the classes
> that need them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/101#issuecomment-143883031>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by benirose** [comment]
Right, it's in our sandbox, but we have admin ui that depends on it!

**Comment by boutell** [comment]
OK, I see. So our admin CSS should carry its own correctly scoped reset
rules.

And it will need them. Because project level CSS could be doing REALLY
weird shit and we do need to play well with that.

On Mon, Sep 28, 2015 at 11:48 PM, benirose <notifications@github.com> wrote:

> Right, it's in our sandbox, but we have admin ui that depends on it!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/101#issuecomment-143935816>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment]
We should look at how we use the apos-ui class, which was intended for this
purpose, and how we make sure we don't overuse it, i.e. it shouldn't be on
a container like an apos-area because that would screw up the user content
inside it. It should only be on an inner div containing buttons, etc.

On Tue, Sep 29, 2015 at 10:52 AM, Tom Boutell <tom@punkave.com> wrote:

> OK, I see. So our admin CSS should carry its own correctly scoped reset
> rules.
>
> And it will need them. Because project level CSS could be doing REALLY
> weird shit and we do need to play well with that.
>
> On Mon, Sep 28, 2015 at 11:48 PM, benirose <notifications@github.com>
> wrote:
>
>> Right, it's in our sandbox, but we have admin ui that depends on it!
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/punkave/apostrophe/issues/101#issuecomment-143935816>
>> .
>>
>
>
>
> --
>
>
> *THOMAS BOUTELL, *DEV & OPS
> P'UNK AVENUE | (215) 755-1330  |  punkave.com
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by benirose** [comment]
Right, I think we're mostly good in that regard.

**Comment by boutell** [comment]
Actually I'm not sure we use apos-ui anymore; poking around it seems like
our markup has lots of apos-ui-* things which presumably have their own
rules. We're going to need to reintroduce apos-ui I think. We could use a
mixin heavily, but that would produce a nasty-huge CSS file.

On Tue, Sep 29, 2015 at 10:56 AM, benirose <notifications@github.com> wrote:

> Right, I think we're mostly good in that regard.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/101#issuecomment-144085881>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment]
We did this for 2.0, we have a reset scoped to `.apos-ui`. It will not be changed for 0.5 as that would be too disruptive now that it's in maintenance support mode.
