### ISSUE TITLE
Pass data to widget editor template

### ISSUE THREAD

**Issue by novascreen** [punkave/apostrophe#111]
I have created a widget called `image` which is based on the `slideshow` and i added additional user options. In my `imageEditor.html` i would like to have some dynamic data. Is that something that is possible or are you planning to add that possibility?

Right now i'm doing this:

    {{ formSelect('proportions', 'Proportions', [{ value: 'keep', label: 'Keep proportions'}, { value: 'img-square', label: 'square'}, { value: 'img-16-9', label: '16:9'}]) }}

But ideally i could set up the possible values in `index.js` or `editor.js`

**Comment by benirose** [comment]
Hi @novascreen, were you able to figure out how to do this?

**Comment by boutell** [comment]
This issue is going away in 0.6, so closing this.

(There is no dynamic data in those templates in 0.5 because they are rendered once and pushed to all editors as DOM templates. In 0.6 it is a nonissue because they are AJAXed in every time making it straightforward to change what they can see. In 0.5 you can work around it though via javascript in your module's editor code.)
