### ISSUE TITLE
how to use websocket ?

### ISSUE THREAD

**Issue by 4stackdev** [punkave/apostrophe#1140]

**Comment by boutell** [comment]
Hi 4stackdev, websockets aren't really related to Apostrophe per se. But Apostrophe apps are node apps, if you want to use socket.io for instance you could add that module to your project and `require` it in an Apostrophe module... etc. In general how-to questions should go to stackoverflow, tagged "apostrophe-cms" so that others can find the information later. Feel free to ask there but be sure to include details of what you are actually trying to do and how Apostrophe fits into the picture.
