### ISSUE TITLE
ajax authentication

### ISSUE THREAD

**Issue by israelidanny** [punkave/apostrophe#136]
I'm trying to authenticate a user for a restricted section of the site, and being unhappy with the login screen, I made a little modal popup in the context of my site. I then POST the username and password to the auth form.

If the credentials are right ,everything is neat. But if they aren't, I can't quite detect it, because in both situations it does a redirect.

Is there any good way for me to be able to authenticate without having to go through the regular login screen?

**Comment by benirose** [comment]
A2 actually has a modal login hidden away for use (shift+esc will bring it up). Additionally, REST protocol does not speak to authorization. I'm curious what your issue with the login page is.

However, we have already done away with appy in the unstable branch (which will become 0.6) and will likely implement some easily extendable functionality in the soon to be developed apostrophe-auth submodule of apostrophe core.

I'll add this ticket to the 0.6 milestone for consideration when working on apostrophe-auth

**Comment by israelidanny** [comment]
The issue with the login page is that for simple ux reasons I don't wanna
transfer a user through yet another screen that looks nothing like my site.

Also if the user entered his details on an Ajax form it seems weird to then
suddenly throw him into another screen upon error ..

I'm very excited towards a more flexible auth module .

**Comment by benirose** [comment]
Thanks for that info Danny. You can actually put a `login.html` template in your `views/global` folder to override the login page. We did this on a website recently to match the style of the website. I think we copied the code from `loginBase.html` in apostrophe core.

I might argue that it makes sense to forward an invalid login to a proper login page (I've seen this done in several apps), but it won't matter once we make auth more flexible, since you'll be able to do what you like :)
