### ISSUE TITLE
jade & sass

### ISSUE THREAD

**Issue by nuky89** [punkave/apostrophe#196]
Hi, I can't get if I could use Jade for template and how.
I would also use sass instead of less.

Thank you.

**Comment by kylestetz** [comment]
Hey @nuky89, good question. We are not supporting Jade at the moment and we have no plans to do so. We rely heavily on some of nunjucks' more advanced features to do our template rendering, and replacing all of that with Jade would be non-trivial.

On the other hand, there's nothing stopping you from using Sass. In your `app.js` configuration you can specify javascript and css `assets` to be pushed to the browser automatically:

```javascript
...
assets: {
    scripts: [ 'masonry.min', 'jquery.tap.min' ],
    stylesheets: ['my-css-file']
},
...
```

You can use a tool like [gulp](http://gulpjs.com/) to automatically compile your Sass to CSS so that Apostrophe can serve it this way.
