### ISSUE TITLE
Docs: Implement Cursor.addFilter to cursor.js

### ISSUE THREAD

**Issue by benirose** [punkave/apostrophe#209]
We want to provide an easy way for subclasses to extend the filter (e.g. add specific filters for the document type they're using).

**Comment by boutell** [comment]
Built it this weekend. And dogfooded it: all the standard filters are added with addFilter.

Example:

```javascript
    self.addFilter('trash', {
      finalize: function() {
        var trash = self.get('trash');
        if (trash === null) {
          return;
        }
        if (!trash) {
          self.and({
            trash: { $exists: 0 }
          });
          return;
        }
        self.and({
          trash: true
        });
      }
    });
```

Your addFilter call will almost always have a "finalize" property which is invoked when the caller is done adding filters and is trying to do real mongo work.

Your finalize function MAY take a callback, but does not have to.

If your finalize function returns "refinalize" or delivers that string to its callback, the finalize process starts again from the top. The autocomplete filter uses this to transform the query into a regular search query after finding relevant complete words.

Your filter MAY have a "set" property, but usually the default behavior:

self.set('yourname', value);

Is all you need. An interesting exception is self.add.

Your `set` function does NOT have to remember to return `self` for chainability, because a wrapper does that for you.

Your filter MAY have a `def` property which is the default value; a `set` call happens with that value if the value is still undefined at finalize time.

Some of the built-in filters don't pass an object at all because their implementation must be part of `toMongo` (it happens after finalize).
