### ISSUE TITLE
Possible replacement for slugify 

### ISSUE THREAD

**Issue by israelidanny** [punkave/apostrophe#241]
I recently saw this fella:
http://pid.github.io/speakingurl/

It claims to do very good slugging in only 12kb minified before compression. 

The current solution requires XRegExp, which is a pretty big sized script to load, and if I'm not mistaken - it is used exclusively for the slugify both back and front end.

Would this be an area of interest for a PR?

**Comment by boutell** [comment]
We're using sluggo:

https://www.npmjs.com/package/sluggo

XRegExp is still a server-side dependency because of our truncatePlaintext
method, but that's not slugging.

On Sun, Apr 26, 2015 at 10:14 AM, Danny Povolotski <notifications@github.com
> wrote:

> I recently saw this fella:
> http://pid.github.io/speakingurl/
>
> It claims to do very good slugging in only 12kb minified before
> compression.
>
> The current solution requires XRegExp, which is a pretty big sized script
> to load, and if I'm not mistaken - it is used exclusively for the slugify
> both back and front end.
>
> Would this be an area of interest for a PR?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/241>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com
