### ISSUE TITLE
Implement data.tabs and data.home such that you don't even have to be on a page to see them but they aren't slow

### ISSUE THREAD

**Issue by jsumnersmith** [punkave/apostrophe#255]
Let's not forget to add a `.peers()` and `.tabs()` filter to the page cursor (similar to `.ancestors()`).

**Comment by boutell** [comment]
tabs() probably should just be something that happens in a pageServe method
in a module somewhere, since it's not actually anything to do with the
current page.

On Thu, May 21, 2015 at 10:15 AM, Joel Smith <notifications@github.com>
wrote:

> Let's not forget to add a .peers() and .tabs() filter to the page cursor
> (similar to .ancestors()).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/255>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by jth-** [comment]
Need to fetch tabs even when not on a page.
