### ISSUE TITLE
Should the apostrophe:reset also create the admin user via apostrophe-users.addFromTask?

### ISSUE THREAD

**Issue by alohaas** [punkave/apostrophe#296]
Assuming apostrophe:reset is still in 0.6

**Comment by boutell** [comment]
Goooooooood question.

It would probably make sense to use callAll() to invoke 'reset' on all
modules, which would give the people module a chance to do something like
adding a default admin... but only after prompting for a password.


On Thu, Jul 16, 2015 at 4:57 PM, Olivia Haas <notifications@github.com>
wrote:

> Assuming apostrophe:reset is still in 0.6
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/296>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by suhmantha1** [comment]
Yes, we decided that apostrophe-db:reset should prompt you to create the admin user

**Comment by boutell** [comment]
... And it'll do that via apos.callAll('dbReset', callback), so that all
modules, not just apostrophe-users, have the option of joining the reset
party.

On Tue, Jul 21, 2015 at 3:45 PM, Samantha Combs <notifications@github.com>
wrote:

> Yes, we decided that apostrophe-db:reset should prompt you to create the
> admin user
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/296#issuecomment-123458936>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com
