### ISSUE TITLE
aphostrophenow.org source

### ISSUE THREAD

**Issue by ranode** [punkave/apostrophe#340]
Hi! We are looking at using this project to create help documentation. The aphostrophenow.org website is very close to what we need. Is that available for us to use?

**Comment by geoffdimasi** [comment]
Sorry! It is not available for use.

**Comment by kylestetz** [comment]
Hey @ranode, just came across this and wanted to ask some clarifying questions because I think we might have misunderstood your question. What did you want to use from our documentation site? It is built on a framework we created called [`habit`](https://github.com/punkave/habit), which is an easy way to turn markdown files into a static site.

You are free to take a look at our documentation site as inspiration— the repo is [here](https://github.com/punkave/apostrophe-documentation)— but we kindly ask that you don't use our branding & design, since our users and customers associate it with the Apostrophe brand and we don't want anyone to get confused!
