### ISSUE TITLE
Login should redirect user to previously requested page

### ISSUE THREAD

**Issue by benirose** [punkave/apostrophe#371]
If a user was on a page that required login, and then logs in, they are redirected to `/`. This ignores the prefix and their previous page request. 

Additionally if your login fails, we are ignoring prefix.

**Comment by boutell** [comment]
Is this 0.5 or 0.6?

On Fri, Oct 16, 2015 at 3:36 PM, Ben Rosenbach <notifications@github.com>
wrote:

> If a user was on a page that required login, and then logs in, they are
> redirected to /. This ignores the prefix and their previous page request.
>
> Additionally if your login fails, we are ignoring prefix.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/371>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by benirose** [comment]
Doh, thought I assigned labels and milestones.

**Comment by boutell** [comment]
How do you know it is ignoring prefix - did you try that? I ask because
res.redirect is patched in the presence of a prefix. (Unless our 0.6 prefix
support is busted, which is entirely possible.)

On Mon, Oct 19, 2015 at 11:26 AM, Ben Rosenbach <notifications@github.com>
wrote:

> Doh, thought I assigned labels and milestones.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/371#issuecomment-149249121>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by benirose** [comment]
Ahh, I forgot we did that. Does passport use res.redirect for the `failureRedirect`? If so that should be good too and I can update this to just be about previously requested page.

**Comment by boutell** [comment]
Best to test and find out

On Tue, Oct 20, 2015 at 11:06 AM, Ben Rosenbach <notifications@github.com>
wrote:

> Reopened #371 <https://github.com/punkave/apostrophe/issues/371>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/371#event-440441661>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment]
Also, this is unit testable? I think?

On Tue, Oct 20, 2015 at 11:10 AM, Tom Boutell <tom@punkave.com> wrote:

> Best to test and find out
>
> On Tue, Oct 20, 2015 at 11:06 AM, Ben Rosenbach <notifications@github.com>
> wrote:
>
>> Reopened #371 <https://github.com/punkave/apostrophe/issues/371>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/punkave/apostrophe/issues/371#event-440441661>.
>>
>
>
>
> --
>
>
> *THOMAS BOUTELL, *DEV & OPS
> P'UNK AVENUE | (215) 755-1330  |  punkave.com
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by benirose** [comment]
Yes I believe so.

**Comment by stuartromanek** [comment]
@boutell Whats the sitch on this? I must admit I don't even know what state a page should be in to trigger a login redirect to the un-logged in user so I'm unsure how to test.

**Comment by boutell** [comment]
This exists as an optional module. The documentation covers the scenario well: the page is set to "login required," you're not logged in, you get invited to log in instead of just 404'ing on the spot.

There are security pros and cons to doing this, performance pros and cons too, all well discussed in the docs:

https://www.npmjs.com/package/apostrophe-second-chance-login
