### ISSUE TITLE
How to use 3rd Part NPM modules within my site.

### ISSUE THREAD

**Issue by rwatts3** [punkave/apostrophe#395]
Greetings,

What is the best way to load assets from an npm module for the site.
For example I am using bootstrap and fontawesome on a site, and Currently I am using `lib/locals.js` , and simply exporting the require to that third party asset via `module.exports`. Is this the right way to do this or should this be done a different way.

**Comment by boutell** [comment]
Hi Ryan,

Are we talking about javascript you want to see in the browser? Just to be
clear...

On Sat, Dec 19, 2015 at 1:01 PM, Ryan Watts <notifications@github.com>
wrote:

> Greetings,
>
> What is the best way to load assets from an npm module for the site.
> For example I am using bootstrap and fontawesome on a site, and Currently
> I am using lib/locals.js , and simply exporting the require to that third
> party asset via module.exports. Is this the right way to do this or
> should this be done a different way.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/395>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by rwatts3** [comment]
Hi , it could be JavaScript or CSS.  This particular case I am wanting to use bootstrap so I would need the bootstrap js CSS as well as jquery npm packages.  I know the easiest way to do this is just include the files locally or write add them directly to the head in base.html but I just want to make sure I'm not missing out on the powers of apostrophe.  For instance is there a simple way to add them or load them via app.js from require or should all 3rd party /framework libraries be loaded directly in the public vendor folder.

**Comment by rwatts3** [comment]
Hi, 

Is there any update on this question ?

**Comment by benirose** [comment]
Sorry Ryan! We had a recent project that used Bootstrap, so we just recently made sure our styles were scoped to work with that framework. 

As far as how to include it there are a number of ways you could do it, none of them wrong. You could use the LESS source and have it compile at server start with the rest of your LESS. This is a bit more complicated because you'll need to find a way to work in the [Autoprefixer](http://getbootstrap.com/getting-started/#download-autoprefixer) module that Bootstrap requires during the LESS compilation process at server start up. We had a hard time getting this working so we went a different route, but I'm pretty positive it can be done. The benefit of using the LESS is that you can override/change LESS variables in your code.

If you don't need that, you can just use the compiled CSS. Apostrophe is happy to use either, and you can include them in your project by adding them to the `assets` option in your `app.js`. Apostrophe will figure out if it needs to compile the LESS or not. We usually recommend using a vendors folder to keep 3rd party code separate from your own.

```javascript
// files in the public folder, no need for extensions
assets: {
  scripts: ['site', 'vendor/bootstrap'], 
  stylesheets: ['site','vendor/bootstrap'] 
}
```

This is the typical way of including LESS/CSS and Javascript in Apostrophe (although you can take a look at the [Apostrophe-Browserify](https://github.com/punkave/apostrophe-browserify) module for using Browserify for site specific client-side JS). Keep in mind if you change any folder structure from what Bootstrap expects, you might have to update the location of the fonts in the code. Also, you should be ok to use the non-minified versions of the code, since Apostrophe will minify them on production for you (assuming you have that value set in your `data/local.js`).

As far as other ways to load them in, I'm not totally sure how loading a client side framework via a `require` in node works or is useful, but I imagine there's a way. You can also use something like Bower to pull the files in and move them, or use a `.bowerrc` file to install them in the proper location.

I hope that helps answer the question. If you found it useful and were able to get it working, we could use a [HOWTO](http://apostrophenow.org/howtos/index.html) on this topic (specific to bootstrap). If you feel like giving back and want to make a pull request to the [Apostrophe-Documentation](https://github.com/punkave/apostrophe-documentation) repo, we would be very grateful!

Lastely @boutell can you double check everything I just said to make sure I didn't flub anything? :)

**Comment by rwatts3** [comment]
@benirose Thank you for that follow-up.
Your response painted a more clear picture than what I previously had. I believe with the instructions above , and options I should be able to get things working smoothly. 

Thanks again for your time, 

I'd be more than happy to contribute where I can. I'll spend a little more time to learn Apostrophe and the ecosystem behind it, before I begin, but I will definitely contribute.

Ryan

**Comment by benirose** [comment]
No problem! Feel free to ask any other questions you have, our documentation can be limited on common things were used to doing all the time.

**Comment by rwatts3** [comment]
Will do, 

While following these steps will this eliminate the issue where bootstrap or the 3rd party framework such as `materializecss` or `foundation` , changes the styling of buttons, dropdowns etc for apostrophe ?

**Comment by boutell** [comment]
Not really, good namespacing is a different issue. In the forthcoming 0.6 version all of our stuff is namespaced with an apos prefix, no exceptions.

**Comment by boutell** [comment]
... Although we'll still be requiring the presence of fontawesome, in a more current version of course.

**Comment by rwatts3** [comment]
Awesome, forgive me for the lack of knowledge is there a trello board or tentative launch date for 0.6?

**Comment by boutell** [comment]
We're close! Our next client project will likely be done with it, which will fill the remaining obvious gaps for practical use, and then it'll be npm published and we'll be pushing out documentation. It's a significant bc break, so 0.5 will be part of our lives for some time yet too.

**Comment by benirose** [comment]
@rwatts3 you can take a look at the issues section to see how many tickets we have assigned to the 0.6 milestone. Some of those need some clean up, and some aren't required for official 0.6, but you'll still get the general idea.

As far as other frameworks, we definitely made steps to fix any scoping of apostrophe/admin styles to not overlap with frameworks, but there may still be some things we missed. Feel free to let us know if we missed any.

**Comment by rwatts3** [comment]
Sounds good thank you @boutell and @benirose
