### ISSUE TITLE
bson Module not found

### ISSUE THREAD

**Issue by mavieth** [punkave/apostrophe#453]
~/Sites/apostrophe-sandbox-> node app apostrophe:reset
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
[Error: failed to connect to [localhost:27017]]

Any idea why this would happen?

**Comment by boutell** [comment]
That's not the real error (:

The error is:

[Error: failed to connect to [localhost:27017]]

Translation: "mongodb ain't running on this computer right now." (:

The other message is a warning because apparently you're not set up to
compile binary modules, like the faster version of the BSON serializer, but
there is a fallback pure JavaScript version that works fine.

On Mon, Mar 7, 2016 at 4:41 PM, Michael Vieth <notifications@github.com>
wrote:

> ~/Sites/apostrophe-sandbox-> node app apostrophe:reset
> { [Error: Cannot find module '../build/Release/bson'] code:
> 'MODULE_NOT_FOUND' }
> js-bson: Failed to load c++ bson extension, using pure JS version
> [Error: failed to connect to [localhost:27017]]
>
> Any idea why this would happen?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/453>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com
