### ISSUE TITLE
Not authorized... 

### ISSUE THREAD

**Issue by JemiloII** [punkave/apostrophe#475]
This is the error I am getting.

Error
```js
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
{ [MongoError: not authorized on memes to execute command { update: "sessions", writeConcern: { w: 1 }, ordered: true, updates: [ { q: { expires: { $exists: 0 } }, u: { $set: { expires: new Date(1460349834446) } }, multi: true, upsert: false } ] }]
  name: 'MongoError',
  ok: 0,
  errmsg: 'not authorized on memes to execute command { update: "sessions", writeConcern: { w: 1 }, ordered: true, updates: [ { q: { expires: { $exists: 0 } }, u: { $set: { expires: new Date(1460349834446) } }, multi: true, upsert: false } ] }',
  code: 13 }
```

The db section from local.js
```js
db: {
   uri: 'mongodb://localhost:27017/apostrophe'
}
```

mongo commands through docker

`docker run --name apostrophe-mongo -p 27017:27017 -p 27018:27018 -p 27019:27019 -v /mongo/data/db:/data/db -d mongo --auth`
`docker exec -it apostrophe-mongo mongo`
`use admin`
`db.createUser({ user: "admin", pwd: "password", roles:[{role: "root", db: "admin" }]});`
`use apostrophe`
`db.createUser({ user: "hands", pwd: "cameron", roles:[{role: "readWrite", db: "apostrophe" }]});`

**Comment by cfinefield** [comment]
Terrible. I'm having the same issue.

**Comment by boutell** [comment]
This is a mongodb permissions issue. It has nothing to do with Apostrophe
itself.

You've created permissions for specific users in mongodb, and you've left
our local.js configured with a default mongodb URI that doesn't have a user
and password in it. So at that point it's not surprising that it doesn't
work.

Since two people are reporting this, may I ask if there's a recipe
somewhere where you're finding this? We don't have a docker recipe,
officially, but maybe someone else does, and they left out a key step about
configuring local.js correctly to actually use the credentials being set up.

On Mon, Mar 28, 2016 at 1:07 AM, cfinefield <notifications@github.com>
wrote:

> Terrible. I'm having the same issue.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/475#issuecomment-202236203>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by JemiloII** [comment]
That's the thing... I've created a mongo user, and set it up with the database table. Then added it to local.js. Is there another step that I am missing?

mongo
`use apostrophe`
`db.createUser({ user: "hands", pwd: "cameron", roles:[{role: "readWrite", db: "apostrophe" }]});`

local.js
```
db: {
   uri: 'mongodb://hands:cameron@localhost:27017/apostrophe'
}
```

**Comment by boutell** [comment]
Hmm, this local.js is different from what you pasted before. The previous
local.js did not have the username and password.

I would expect this second version of local.js to work. If it doesn't, I'm
not sure why, but keep in mind that we're just passing the uri directly to
the mongodb npm package. We're not parsing it or interfering with it in any
way.



On Wed, Mar 30, 2016 at 3:04 PM, Brian M. Jemilo II <
notifications@github.com> wrote:

> That's the thing... I've created a mongo user, and set it up with the
> database table. Then added it to local.js. Is there another step that I am
> missing?
>
> mongo
> use apostrophe
> db.createUser({ user: "hands", pwd: "cameron", roles:[{role: "readWrite",
> db: "apostrophe" }]});
>
> local.js
>
> db: {
>    uri: 'mongodb://hands:cameron@localhost:27017/apostrophe'
> }
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/475#issuecomment-203585987>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by JemiloII** [comment]
yeah i have no clue. i'm bongled by this. I decided to run mongo without --auth, and I can connect, but im guessing, its not a good idea for production use. I just wanted to see if it'd do something.

**Comment by boutell** [comment]
You can actually do that if you lock down mongod.conf so that connections
are only accepted from localhost. Consider that someone who has a shell on
localhost probably already has access to the mongo password, etc.

Only a valid statement for a single-server setup of course.

On Wed, Mar 30, 2016 at 4:54 PM, Brian M. Jemilo II <
notifications@github.com> wrote:

> yeah i have no clue. i'm bongled by this. I decided to run mongo without
> --auth, and I can connect, but im guessing, its not a good idea for
> production use. I just wanted to see if it'd do something.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/475#issuecomment-203633056>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by JemiloII** [comment]
Do you think it has anything to do with me using mongo 3.x versions?

**Comment by boutell** [comment]
I suggest taking it up on the mongodb irc channel. Focus on the fact that
you're using a certain URI and creating a user a certain way and don't
bring Apostrophe into it right away.

On Wed, Mar 30, 2016 at 5:00 PM, Brian M. Jemilo II <
notifications@github.com> wrote:

> Do you think it has anything to do with me using mongo 3.x versions?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/475#issuecomment-203634848>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by JemiloII** [comment]
sounds like a plan, thanks for the help
