### ISSUE TITLE
Question : How to set db uri from using 0.6 unstable branch.

### ISSUE THREAD

**Issue by rwatts3** [punkave/apostrophe#610]
Greetings,

I am  attempting to set the db uri, to a database that is not on localhost. 
Adding `db :  {uri: .....}` as well as `uri : ...` 
appears to not be successful. I see in the apostrophe-db module we are looking for `uri` within the options scope , however it is not clear where to pass the options. or how to pass them to the module.

**Comment by rwatts3** [comment]
Well it never fails :/ 
I always seem to spontaneously answer my own question after posting to Github. I suppose it's the Zen of Github that causes this. 

For anyone else that had this forehead smacker here is the solution. 

All modules now, can be passed to app.js with "options". 

```js
apostrophe-db: {
   uri: '....'
}
```

**Comment by boutell** [comment]
I see you figured it out! But here's a more detailed answer for any interested party.

You could do this in app.js:

```
var apos = require('apostrophe')({
  shortName: 'mysite', /* and more options... */
  modules: {
    'apostrophe-db': {
      uri: 'mongodb://localhost:27017/user:password@mydb'
    }
  }
});
```

You can also do it in `lib/modules/apostrophe-db/index.js` in your project, which automatically extends that module if it exists. You can do a lot with that, but here we just set an option:

```
module.exports = {
  uri: 'mongodb://localhost:27017/user:password@mydb'
};
```

Or you can do it in `data/local.js`, which gets merged with the configuration object in `app.js` and is never deployed by our standard stagecoach deployment scripts, so that it can be different on each server:

```
module.exports = {
  'apostrophe-db': {
    uri: 'mongodb://localhost:27017/user:password@mydb'
  }
}
```

These are the patterns for configuring any module.

Hope this is helpful!

**Comment by rwatts3** [comment]
Thank you Tom.  I've also submitted a PR to stagecoach to allow
compatibility for 0.6
