### ISSUE TITLE
pageBeforeSend(req) simultaneously gets called in all modules which have inherited apostrophe-pieces-pages

### ISSUE THREAD

**Issue by kmanaseryan** [punkave/apostrophe#845]
For example there are two modules that extend `apostrophe-pieces-pages`. As follows:

_modules/lib/articles/index.js_
```
module.exports = {
    extend: 'apostrophe-pieces'
    ...
}
```

_modules/lib/articles-pages/index.js_
```
module.exports = {
    extend: 'apostrophe-pieces-pages',
    perPage: 3,
    ....
   construct: function (self, options) {
   var superPageBeforeSend = self.pageBeforeSend;
        self.pageBeforeSend = function(req){
             var pieces = req.data.pieces;
             if(!pieces)
                return superPageBeforeSend(req);
             console.log(pieces) //this also shows profile pieces
        }
}

``` 

_modules/lib/profiles/index.js_
```
module.exports = {
    extend: 'apostrophe-pieces'
    ...
}
```

_modules/lib/profiles-pages/index.js_
```
module.exports = {
    extend: 'apostrophe-pieces-pages',
    perPage: 3,
    ....
   construct: function (self, options) {
   var superPageBeforeSend = self.pageBeforeSend;
        self.pageBeforeSend = function(req){
             var pieces = req.data.pieces;
             if(!pieces)
                return superPageBeforeSend(req);
             console.log(pieces) //this also shows article pieces
        }
}

``` 

So how I know the idea of having [Moog](http://apostrophecms.org/docs/glossary.html#moog-type) type is to isolate the modules from each other, whereas in this case they share the same function.

**Comment by boutell** [comment]
Hi Karlen,

`pageBeforeSend` is a method which is invoked on *every* module that has one, every time a page is rendered. You can see documentation to this effect in the explanation of the method for various modules. This actually has nothing to do with subclassing `apostrophe-pieces-pages`. It happens because the `sendPage` method invokes `callAll`:

```
      return self.apos.callAll('pageBeforeSend', req, function(err) { ... }
```

This is intentionally done to give every interested module a chance to load resources just before a page is rendered and optionally attach them to `req.data` for use by templates.

It is therefore your responsibility when implementing this method to make sure this particular request is relevant to your module, for instance by checking that `req.page` exists and `req.page.type` is what you are looking for.
