### ISSUE TITLE
Add Focus hotspot to an Image relationship

### ISSUE THREAD

**Issue by stuartromanek** [punkave/apostrophe#862]
It could be as simple as adding a focus icon to the relationship controls and placing a dot somewhere on the image, in the same context as a crop would take place
![apostrophe-focus](https://cloud.githubusercontent.com/assets/1889830/24808678/bb28b8ca-1b8a-11e7-88af-ae4f65134a65.jpg)

We could do some nice front-end pulse effect in its idle state to alert the user to its location.

What does this mean for the template implementation? background images? IMGs positioned with js?

**Comment by agilbert** [comment]
Apostrophe's primary responsibilities as it relates to this ticket:

- provide a good UI for setting the focal point (check, the above looks great)
- providing the data on the focal point to the template in an elegant 

There may be a use case for actually implementing the focal point data on the front-end in a default image widget, if so we can talk through that implementation in a separate ticket.

**Comment by stuartromanek** [comment]
Track time on this

**Comment by boutell** [comment]
See the focal-point-editor branch. It works. However we shouldn't merge this without an example of a frontend implementation. Maybe the frontend implementation isn't part of the core. The focal point editor is currently part of the core because it's rather deeply embedded in the attachment and images modules.

**Comment by stuartromanek** [comment]
Maybe you forgot to push or something @boutell ? This branch is very broken, stubbed in functions, lines of nunjucks in the js, etc.

**Comment by boutell** [comment]
Sorry, I think I didn't push my continued work on it, but there's still a
bug and I can probably finish sorting out why most quickly... The y
coordinates are coming out strange. I am almost out of battery but maybe I
can push my latest on the Amtrak wifi... Bam! Did it with 2% left.

If you want to pursue this the issue is that while the point looks right
when you edit save and re edit, I'm getting coordinates beyond the image in
the actual data, so I know I'm not scaling something right yet. Probably
easiest for me to complete the work but I certainly won't try before Monday.

On Jul 14, 2017 8:03 AM, "Stuart Romanek" <notifications@github.com> wrote:

Maybe you forgot to push or something @boutell <https://github.com/boutell>
? This branch is very broken, stubbed in functions, lines of nunjucks in
the js, etc.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/punkave/apostrophe/issues/862#issuecomment-315382315>,
or mute the thread

**Comment by stuartromanek** [comment]
U R a Titan

**Comment by boutell** [comment]
This was implemented and published. It's not a 1-1 match with the design because editing inline in the manage space is not done for anything else and would have been a major lift, also raises questions about what happens if you click on other stuff outside that space, etc. There's a hotspot picker modal, like the cropping modal.

**Comment by stuartromanek** [comment]
How do I enable this/check this out @boutell ?

**Comment by boutell** [comment]
http://apostrophecms.org/docs/tutorials/howtos/responsive-images.html
