### ISSUE TITLE
Functionality for contextual true for pieces should be default behavior

### ISSUE THREAD

**Issue by austinstarin** [punkave/apostrophe#900]

**Comment by boutell** [comment]
Pretty much agree — right now however contextual: true changes what happens when you click on a title in the manage modal, right? So the replacement can't just force that on all the time and call it a day — it has to consider whether `._url` is available for this piece, and should probably offer ways to access both the modal and the show page, as discussed.

**Comment by austinstarin** [comment]
Thanks for summarizing that @boutell!

**Comment by stuartromanek** [comment]
UX consideration for the external link inside the manager modal

**Comment by stuartromanek** [comment]
Create a flag for `showPage: false`

**Comment by boutell** [comment]
There is a bc break here:

* Existing site, has pieces, they don't have working `show.html` templates because nobody's linking to them (this is bad, but we've done it ourselves)
* npm update happens
* Now creating a new piece in "manage" redirects you to a busted template, 500 error.

Less bad but still a UX problem:

* Existing site, has pieces, they have working `show.html` templates but they don't have any contextually edited content.
* npm update happens
* Now creating a new piece in "manage" redirects you to a page where you can preview, I guess, but you can't edit anything, so you probably would have been happier staying in the "manage" view.

These issues can be addressed via `showPage: false` but that requires the dev to mess with their code to get their site going again = a bc break.

We can discuss but I'm not sure I see a good way forward here.

**Comment by stuartromanek** [comment]
Lets list out all the features that `contextual : true` enables and see if we can't break some of these out into separate flags.
