### ISSUE TITLE
Way of checking whether area is empty in template logic

### ISSUE THREAD

**Issue by grdunn** [punkave/apostrophe#957]
basically a `2.x` version of this `0.5` method:
```
aposSingletonIsEmpty(page, 'foo', 'video') 
```

**Comment by boutell** [comment]
See PR #997

**Comment by boutell** [comment]
It turns out our htmlToPlaintext method already converts block element opening tags to newlines :slightly_smiling_face:

And we are already using that method plus trim to check for emptiness.

So we can count newlines before we trim, and if we see more than one, consider it nonempty.

We should add this before publishing the feature although the original PR has been merged.

**Comment by stuartromanek** [comment]
`{{ apos.areas.isEmpty(context, name) }}` now does this in 2.0
